approvedGitRepositories: []

catalogs:
  dev:
    "@ai-crew-suite/crew-cli": ^0.0.5
    "@ai-crew-suite/typescript-shared-config": ^0.0.2
    "@changesets/cli": ^3.0.3
    "@playwright/test": ^1.63.0
    "@tsconfig/node22": 22.0.6
    "@types/node": ^22.20.5
    "@typescript-eslint/eslint-plugin": ^8.70.1
    "@typescript-eslint/parser": ^8.70.1
    "@vercel/ncc": ^0.45.0
    eslint: ^10.11.0
    husky: ^9.1.7
    jiti: ^2.7.0
    lint-staged: ^17.6.0
    node-actionlint: ^1.2.2
    openapi-typescript: ^7.13.0
    prettier: ^3.9.9
    turbo: ^2.11.7
    typescript: 6.0.3
    vite: ^8.3.1
    vitest: ^5.0.2
  prod:
    "@actions/core": ^3.0.1
    "@actions/github": ^9.1.1

enableGlobalCache: false

enableHardenedMode: true

enableImmutableCache: true

enableScripts: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0086
    level: discard

nodeLinker: node-modules

npmAlwaysAuth: false

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@ai-crew-suite/*"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  vitest@*:
    dependencies:
      "@types/node": "*"

unsafeHttpWhitelist: []

yarnPath: .yarn/releases/yarn-4.18.1.cjs
